# Generated by Django 5.1.2 on 2024-10-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='background_image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
