# Generated by Django 5.1.2 on 2024-10-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_about_image_alter_banner_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
