# Generated by Django 5.1.2 on 2024-10-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('award', 'Award'), ('star', 'Star'), ('trophy', 'Trophy')], default='trophy', max_length=10)),
            ],
        ),
    ]
