# Generated by Django 5.1.2 on 2024-10-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivement',
            name='icon',
            field=models.CharField(choices=[('Award', 'Award'), ('Star', 'Star'), ('Trophy', 'Trophy')], default='trophy', max_length=10),
        ),
    ]
